def config = [
  repo: 'git@gitlab.saritasa.com:saritasa.com/saritasa2019.git',
  branch: "${env.GIT_BRANCH}",
  server: 'saritasa2021.saritasa-hosting.com',
  location: '/home/saritasa2021/web/saritasa2021.saritasa-hosting.com/private/',
]

node {
  stage('scm') {
    checkout scm
  }
  stage('ansistrano-deploy') {
    env.ANSIBLE_HOST_KEY_CHECKING='False'
    env.ANSIBLE_REMOTE_USER='saritasa2021'
    env.ANSIBLE_SSH_ARGS='-C -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes'
    sshagent(['jenkins-ssh-credential']) {
        sh(script: "ansible-playbook -i ${config.server}, \
        artifacts/ansistrano-deploy.yml \
        --extra-vars \
        'deploy_path=${config.location} deploy_repo=${config.repo} deploy_branch=${config.branch}'")
    }
  }
}

